/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icebreaker.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.exception.LocaleException;
import com.liferay.portal.kernel.model.BaseModel;
import com.liferay.portal.kernel.model.GroupedModel;
import com.liferay.portal.kernel.model.LocalizedModel;
import com.liferay.portal.kernel.model.ShardedModel;
import com.liferay.portal.kernel.model.StagedAuditedModel;

import java.util.Date;
import java.util.Locale;
import java.util.Map;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the IcebreakerEntry service. Represents a row in the &quot;ICEBREAKER_IcebreakerEntry&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icebreaker.model.impl.IcebreakerEntryModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icebreaker.model.impl.IcebreakerEntryImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see IcebreakerEntry
 * @generated
 */
@ProviderType
public interface IcebreakerEntryModel
	extends BaseModel<IcebreakerEntry>, GroupedModel, LocalizedModel,
			ShardedModel, StagedAuditedModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a icebreaker entry model instance should use the {@link IcebreakerEntry} interface instead.
	 */

	/**
	 * Returns the primary key of this icebreaker entry.
	 *
	 * @return the primary key of this icebreaker entry
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this icebreaker entry.
	 *
	 * @param primaryKey the primary key of this icebreaker entry
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the uuid of this icebreaker entry.
	 *
	 * @return the uuid of this icebreaker entry
	 */
	@AutoEscape
	@Override
	public String getUuid();

	/**
	 * Sets the uuid of this icebreaker entry.
	 *
	 * @param uuid the uuid of this icebreaker entry
	 */
	@Override
	public void setUuid(String uuid);

	/**
	 * Returns the icebreaker entry ID of this icebreaker entry.
	 *
	 * @return the icebreaker entry ID of this icebreaker entry
	 */
	public long getIcebreakerEntryId();

	/**
	 * Sets the icebreaker entry ID of this icebreaker entry.
	 *
	 * @param icebreakerEntryId the icebreaker entry ID of this icebreaker entry
	 */
	public void setIcebreakerEntryId(long icebreakerEntryId);

	/**
	 * Returns the group ID of this icebreaker entry.
	 *
	 * @return the group ID of this icebreaker entry
	 */
	@Override
	public long getGroupId();

	/**
	 * Sets the group ID of this icebreaker entry.
	 *
	 * @param groupId the group ID of this icebreaker entry
	 */
	@Override
	public void setGroupId(long groupId);

	/**
	 * Returns the company ID of this icebreaker entry.
	 *
	 * @return the company ID of this icebreaker entry
	 */
	@Override
	public long getCompanyId();

	/**
	 * Sets the company ID of this icebreaker entry.
	 *
	 * @param companyId the company ID of this icebreaker entry
	 */
	@Override
	public void setCompanyId(long companyId);

	/**
	 * Returns the user ID of this icebreaker entry.
	 *
	 * @return the user ID of this icebreaker entry
	 */
	@Override
	public long getUserId();

	/**
	 * Sets the user ID of this icebreaker entry.
	 *
	 * @param userId the user ID of this icebreaker entry
	 */
	@Override
	public void setUserId(long userId);

	/**
	 * Returns the user uuid of this icebreaker entry.
	 *
	 * @return the user uuid of this icebreaker entry
	 */
	@Override
	public String getUserUuid();

	/**
	 * Sets the user uuid of this icebreaker entry.
	 *
	 * @param userUuid the user uuid of this icebreaker entry
	 */
	@Override
	public void setUserUuid(String userUuid);

	/**
	 * Returns the user name of this icebreaker entry.
	 *
	 * @return the user name of this icebreaker entry
	 */
	@AutoEscape
	@Override
	public String getUserName();

	/**
	 * Sets the user name of this icebreaker entry.
	 *
	 * @param userName the user name of this icebreaker entry
	 */
	@Override
	public void setUserName(String userName);

	/**
	 * Returns the create date of this icebreaker entry.
	 *
	 * @return the create date of this icebreaker entry
	 */
	@Override
	public Date getCreateDate();

	/**
	 * Sets the create date of this icebreaker entry.
	 *
	 * @param createDate the create date of this icebreaker entry
	 */
	@Override
	public void setCreateDate(Date createDate);

	/**
	 * Returns the modified date of this icebreaker entry.
	 *
	 * @return the modified date of this icebreaker entry
	 */
	@Override
	public Date getModifiedDate();

	/**
	 * Sets the modified date of this icebreaker entry.
	 *
	 * @param modifiedDate the modified date of this icebreaker entry
	 */
	@Override
	public void setModifiedDate(Date modifiedDate);

	/**
	 * Returns the status of this icebreaker entry.
	 *
	 * @return the status of this icebreaker entry
	 */
	public int getStatus();

	/**
	 * Sets the status of this icebreaker entry.
	 *
	 * @param status the status of this icebreaker entry
	 */
	public void setStatus(int status);

	/**
	 * Returns the name of this icebreaker entry.
	 *
	 * @return the name of this icebreaker entry
	 */
	@AutoEscape
	public String getName();

	/**
	 * Sets the name of this icebreaker entry.
	 *
	 * @param name the name of this icebreaker entry
	 */
	public void setName(String name);

	/**
	 * Returns the type of this icebreaker entry.
	 *
	 * @return the type of this icebreaker entry
	 */
	@AutoEscape
	public String getType();

	/**
	 * Sets the type of this icebreaker entry.
	 *
	 * @param type the type of this icebreaker entry
	 */
	public void setType(String type);

	/**
	 * Returns the ib ip of this icebreaker entry.
	 *
	 * @return the ib ip of this icebreaker entry
	 */
	@AutoEscape
	public String getIbIp();

	/**
	 * Sets the ib ip of this icebreaker entry.
	 *
	 * @param ibIp the ib ip of this icebreaker entry
	 */
	public void setIbIp(String ibIp);

	/**
	 * Returns the ib port of this icebreaker entry.
	 *
	 * @return the ib port of this icebreaker entry
	 */
	@AutoEscape
	public String getIbPort();

	/**
	 * Sets the ib port of this icebreaker entry.
	 *
	 * @param ibPort the ib port of this icebreaker entry
	 */
	public void setIbPort(String ibPort);

	/**
	 * Returns the ib user ID of this icebreaker entry.
	 *
	 * @return the ib user ID of this icebreaker entry
	 */
	@AutoEscape
	public String getIbUserId();

	/**
	 * Sets the ib user ID of this icebreaker entry.
	 *
	 * @param ibUserId the ib user ID of this icebreaker entry
	 */
	public void setIbUserId(String ibUserId);

	/**
	 * Returns the ib user password of this icebreaker entry.
	 *
	 * @return the ib user password of this icebreaker entry
	 */
	@AutoEscape
	public String getIbUserPassword();

	/**
	 * Sets the ib user password of this icebreaker entry.
	 *
	 * @param ibUserPassword the ib user password of this icebreaker entry
	 */
	public void setIbUserPassword(String ibUserPassword);

	/**
	 * Returns the description of this icebreaker entry.
	 *
	 * @return the description of this icebreaker entry
	 */
	public String getDescription();

	/**
	 * Returns the localized description of this icebreaker entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param locale the locale of the language
	 * @return the localized description of this icebreaker entry
	 */
	@AutoEscape
	public String getDescription(Locale locale);

	/**
	 * Returns the localized description of this icebreaker entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param locale the local of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this icebreaker entry. If <code>useDefault</code> is <code>false</code> and no localization exists for the requested language, an empty string will be returned.
	 */
	@AutoEscape
	public String getDescription(Locale locale, boolean useDefault);

	/**
	 * Returns the localized description of this icebreaker entry in the language. Uses the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @return the localized description of this icebreaker entry
	 */
	@AutoEscape
	public String getDescription(String languageId);

	/**
	 * Returns the localized description of this icebreaker entry in the language, optionally using the default language if no localization exists for the requested language.
	 *
	 * @param languageId the ID of the language
	 * @param useDefault whether to use the default language if no localization exists for the requested language
	 * @return the localized description of this icebreaker entry
	 */
	@AutoEscape
	public String getDescription(String languageId, boolean useDefault);

	@AutoEscape
	public String getDescriptionCurrentLanguageId();

	@AutoEscape
	public String getDescriptionCurrentValue();

	/**
	 * Returns a map of the locales and localized descriptions of this icebreaker entry.
	 *
	 * @return the locales and localized descriptions of this icebreaker entry
	 */
	public Map<Locale, String> getDescriptionMap();

	/**
	 * Sets the description of this icebreaker entry.
	 *
	 * @param description the description of this icebreaker entry
	 */
	public void setDescription(String description);

	/**
	 * Sets the localized description of this icebreaker entry in the language.
	 *
	 * @param description the localized description of this icebreaker entry
	 * @param locale the locale of the language
	 */
	public void setDescription(String description, Locale locale);

	/**
	 * Sets the localized description of this icebreaker entry in the language, and sets the default locale.
	 *
	 * @param description the localized description of this icebreaker entry
	 * @param locale the locale of the language
	 * @param defaultLocale the default locale
	 */
	public void setDescription(
		String description, Locale locale, Locale defaultLocale);

	public void setDescriptionCurrentLanguageId(String languageId);

	/**
	 * Sets the localized descriptions of this icebreaker entry from the map of locales and localized descriptions.
	 *
	 * @param descriptionMap the locales and localized descriptions of this icebreaker entry
	 */
	public void setDescriptionMap(Map<Locale, String> descriptionMap);

	/**
	 * Sets the localized descriptions of this icebreaker entry from the map of locales and localized descriptions, and sets the default locale.
	 *
	 * @param descriptionMap the locales and localized descriptions of this icebreaker entry
	 * @param defaultLocale the default locale
	 */
	public void setDescriptionMap(
		Map<Locale, String> descriptionMap, Locale defaultLocale);

	@Override
	public String[] getAvailableLanguageIds();

	@Override
	public String getDefaultLanguageId();

	@Override
	public void prepareLocalizedFieldsForImport() throws LocaleException;

	@Override
	public void prepareLocalizedFieldsForImport(Locale defaultImportLocale)
		throws LocaleException;

}