/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icebreaker.model;

import com.liferay.portal.kernel.bean.AutoEscape;
import com.liferay.portal.kernel.model.BaseModel;

import org.osgi.annotation.versioning.ProviderType;

/**
 * The base model interface for the JobData service. Represents a row in the &quot;ICEBREAKER_JobData&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This interface and its corresponding implementation <code>com.osp.icebreaker.model.impl.JobDataModelImpl</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in <code>com.osp.icebreaker.model.impl.JobDataImpl</code>.
 * </p>
 *
 * @author Jerry H. Seo
 * @see JobData
 * @generated
 */
@ProviderType
public interface JobDataModel extends BaseModel<JobData> {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this interface directly. All methods that expect a job data model instance should use the {@link JobData} interface instead.
	 */

	/**
	 * Returns the primary key of this job data.
	 *
	 * @return the primary key of this job data
	 */
	public long getPrimaryKey();

	/**
	 * Sets the primary key of this job data.
	 *
	 * @param primaryKey the primary key of this job data
	 */
	public void setPrimaryKey(long primaryKey);

	/**
	 * Returns the job ID of this job data.
	 *
	 * @return the job ID of this job data
	 */
	public long getJobId();

	/**
	 * Sets the job ID of this job data.
	 *
	 * @param jobId the job ID of this job data
	 */
	public void setJobId(long jobId);

	/**
	 * Returns the input data of this job data.
	 *
	 * @return the input data of this job data
	 */
	@AutoEscape
	public String getInputData();

	/**
	 * Sets the input data of this job data.
	 *
	 * @param inputData the input data of this job data
	 */
	public void setInputData(String inputData);

}