/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icebreaker.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.osp.icebreaker.model.IcebreakerEntry;
import com.osp.icebreaker.service.IcebreakerEntryLocalService;
import com.osp.icebreaker.service.persistence.IcebreakerEntryPersistence;
import com.osp.icebreaker.service.persistence.JobDataPersistence;
import com.osp.icebreaker.service.persistence.JobPersistence;
import com.osp.icebreaker.service.persistence.OSPClusterPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the icebreaker entry local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.osp.icebreaker.service.impl.IcebreakerEntryLocalServiceImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see com.osp.icebreaker.service.impl.IcebreakerEntryLocalServiceImpl
 * @generated
 */
public abstract class IcebreakerEntryLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IcebreakerEntryLocalService,
			   IdentifiableOSGiService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>IcebreakerEntryLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.osp.icebreaker.service.IcebreakerEntryLocalServiceUtil</code>.
	 */

	/**
	 * Adds the icebreaker entry to the database. Also notifies the appropriate model listeners.
	 *
	 * @param icebreakerEntry the icebreaker entry
	 * @return the icebreaker entry that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public IcebreakerEntry addIcebreakerEntry(IcebreakerEntry icebreakerEntry) {
		icebreakerEntry.setNew(true);

		return icebreakerEntryPersistence.update(icebreakerEntry);
	}

	/**
	 * Creates a new icebreaker entry with the primary key. Does not add the icebreaker entry to the database.
	 *
	 * @param icebreakerEntryId the primary key for the new icebreaker entry
	 * @return the new icebreaker entry
	 */
	@Override
	@Transactional(enabled = false)
	public IcebreakerEntry createIcebreakerEntry(long icebreakerEntryId) {
		return icebreakerEntryPersistence.create(icebreakerEntryId);
	}

	/**
	 * Deletes the icebreaker entry with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param icebreakerEntryId the primary key of the icebreaker entry
	 * @return the icebreaker entry that was removed
	 * @throws PortalException if a icebreaker entry with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public IcebreakerEntry deleteIcebreakerEntry(long icebreakerEntryId)
		throws PortalException {

		return icebreakerEntryPersistence.remove(icebreakerEntryId);
	}

	/**
	 * Deletes the icebreaker entry from the database. Also notifies the appropriate model listeners.
	 *
	 * @param icebreakerEntry the icebreaker entry
	 * @return the icebreaker entry that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public IcebreakerEntry deleteIcebreakerEntry(
		IcebreakerEntry icebreakerEntry) {

		return icebreakerEntryPersistence.remove(icebreakerEntry);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			IcebreakerEntry.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return icebreakerEntryPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.osp.icebreaker.model.impl.IcebreakerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return icebreakerEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.osp.icebreaker.model.impl.IcebreakerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return icebreakerEntryPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return icebreakerEntryPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return icebreakerEntryPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public IcebreakerEntry fetchIcebreakerEntry(long icebreakerEntryId) {
		return icebreakerEntryPersistence.fetchByPrimaryKey(icebreakerEntryId);
	}

	/**
	 * Returns the icebreaker entry matching the UUID and group.
	 *
	 * @param uuid the icebreaker entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching icebreaker entry, or <code>null</code> if a matching icebreaker entry could not be found
	 */
	@Override
	public IcebreakerEntry fetchIcebreakerEntryByUuidAndGroupId(
		String uuid, long groupId) {

		return icebreakerEntryPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the icebreaker entry with the primary key.
	 *
	 * @param icebreakerEntryId the primary key of the icebreaker entry
	 * @return the icebreaker entry
	 * @throws PortalException if a icebreaker entry with the primary key could not be found
	 */
	@Override
	public IcebreakerEntry getIcebreakerEntry(long icebreakerEntryId)
		throws PortalException {

		return icebreakerEntryPersistence.findByPrimaryKey(icebreakerEntryId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(icebreakerEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(IcebreakerEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("icebreakerEntryId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			icebreakerEntryLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(IcebreakerEntry.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName(
			"icebreakerEntryId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(icebreakerEntryLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(IcebreakerEntry.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("icebreakerEntryId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<IcebreakerEntry>() {

				@Override
				public void performAction(IcebreakerEntry icebreakerEntry)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, icebreakerEntry);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(IcebreakerEntry.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return icebreakerEntryLocalService.deleteIcebreakerEntry(
			(IcebreakerEntry)persistedModel);
	}

	public BasePersistence<IcebreakerEntry> getBasePersistence() {
		return icebreakerEntryPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return icebreakerEntryPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the icebreaker entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the icebreaker entries
	 * @param companyId the primary key of the company
	 * @return the matching icebreaker entries, or an empty list if no matches were found
	 */
	@Override
	public List<IcebreakerEntry> getIcebreakerEntriesByUuidAndCompanyId(
		String uuid, long companyId) {

		return icebreakerEntryPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of icebreaker entries matching the UUID and company.
	 *
	 * @param uuid the UUID of the icebreaker entries
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of icebreaker entries
	 * @param end the upper bound of the range of icebreaker entries (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching icebreaker entries, or an empty list if no matches were found
	 */
	@Override
	public List<IcebreakerEntry> getIcebreakerEntriesByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<IcebreakerEntry> orderByComparator) {

		return icebreakerEntryPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the icebreaker entry matching the UUID and group.
	 *
	 * @param uuid the icebreaker entry's UUID
	 * @param groupId the primary key of the group
	 * @return the matching icebreaker entry
	 * @throws PortalException if a matching icebreaker entry could not be found
	 */
	@Override
	public IcebreakerEntry getIcebreakerEntryByUuidAndGroupId(
			String uuid, long groupId)
		throws PortalException {

		return icebreakerEntryPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the icebreaker entries.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.osp.icebreaker.model.impl.IcebreakerEntryModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of icebreaker entries
	 * @param end the upper bound of the range of icebreaker entries (not inclusive)
	 * @return the range of icebreaker entries
	 */
	@Override
	public List<IcebreakerEntry> getIcebreakerEntries(int start, int end) {
		return icebreakerEntryPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of icebreaker entries.
	 *
	 * @return the number of icebreaker entries
	 */
	@Override
	public int getIcebreakerEntriesCount() {
		return icebreakerEntryPersistence.countAll();
	}

	/**
	 * Updates the icebreaker entry in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param icebreakerEntry the icebreaker entry
	 * @return the icebreaker entry that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public IcebreakerEntry updateIcebreakerEntry(
		IcebreakerEntry icebreakerEntry) {

		return icebreakerEntryPersistence.update(icebreakerEntry);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			IcebreakerEntryLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		icebreakerEntryLocalService = (IcebreakerEntryLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return IcebreakerEntryLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return IcebreakerEntry.class;
	}

	protected String getModelClassName() {
		return IcebreakerEntry.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = icebreakerEntryPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	protected IcebreakerEntryLocalService icebreakerEntryLocalService;

	@Reference
	protected IcebreakerEntryPersistence icebreakerEntryPersistence;

	@Reference
	protected JobPersistence jobPersistence;

	@Reference
	protected JobDataPersistence jobDataPersistence;

	@Reference
	protected OSPClusterPersistence ospClusterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetLinkLocalService
		assetLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}