/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icebreaker.service.base;

import com.liferay.exportimport.kernel.lar.ExportImportHelperUtil;
import com.liferay.exportimport.kernel.lar.ManifestSummary;
import com.liferay.exportimport.kernel.lar.PortletDataContext;
import com.liferay.exportimport.kernel.lar.StagedModelDataHandlerUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.portal.aop.AopService;
import com.liferay.portal.kernel.dao.db.DB;
import com.liferay.portal.kernel.dao.db.DBManagerUtil;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdate;
import com.liferay.portal.kernel.dao.jdbc.SqlUpdateFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DefaultActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQuery;
import com.liferay.portal.kernel.dao.orm.DynamicQueryFactoryUtil;
import com.liferay.portal.kernel.dao.orm.ExportActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.IndexableActionableDynamicQuery;
import com.liferay.portal.kernel.dao.orm.Projection;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.exception.SystemException;
import com.liferay.portal.kernel.model.PersistedModel;
import com.liferay.portal.kernel.module.framework.service.IdentifiableOSGiService;
import com.liferay.portal.kernel.search.Indexable;
import com.liferay.portal.kernel.search.IndexableType;
import com.liferay.portal.kernel.service.BaseLocalServiceImpl;
import com.liferay.portal.kernel.service.PersistedModelLocalService;
import com.liferay.portal.kernel.service.persistence.BasePersistence;
import com.liferay.portal.kernel.transaction.Transactional;
import com.liferay.portal.kernel.util.OrderByComparator;
import com.liferay.portal.kernel.util.PortalUtil;

import com.osp.icebreaker.model.OSPCluster;
import com.osp.icebreaker.service.OSPClusterLocalService;
import com.osp.icebreaker.service.persistence.IcebreakerEntryPersistence;
import com.osp.icebreaker.service.persistence.JobDataPersistence;
import com.osp.icebreaker.service.persistence.JobPersistence;
import com.osp.icebreaker.service.persistence.OSPClusterPersistence;

import java.io.Serializable;

import java.util.List;

import javax.sql.DataSource;

import org.osgi.service.component.annotations.Reference;

/**
 * Provides the base implementation for the osp cluster local service.
 *
 * <p>
 * This implementation exists only as a container for the default service methods generated by ServiceBuilder. All custom service methods should be put in {@link com.osp.icebreaker.service.impl.OSPClusterLocalServiceImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see com.osp.icebreaker.service.impl.OSPClusterLocalServiceImpl
 * @generated
 */
public abstract class OSPClusterLocalServiceBaseImpl
	extends BaseLocalServiceImpl
	implements AopService, IdentifiableOSGiService, OSPClusterLocalService {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. Use <code>OSPClusterLocalService</code> via injection or a <code>org.osgi.util.tracker.ServiceTracker</code> or use <code>com.osp.icebreaker.service.OSPClusterLocalServiceUtil</code>.
	 */

	/**
	 * Adds the osp cluster to the database. Also notifies the appropriate model listeners.
	 *
	 * @param ospCluster the osp cluster
	 * @return the osp cluster that was added
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public OSPCluster addOSPCluster(OSPCluster ospCluster) {
		ospCluster.setNew(true);

		return ospClusterPersistence.update(ospCluster);
	}

	/**
	 * Creates a new osp cluster with the primary key. Does not add the osp cluster to the database.
	 *
	 * @param clusterId the primary key for the new osp cluster
	 * @return the new osp cluster
	 */
	@Override
	@Transactional(enabled = false)
	public OSPCluster createOSPCluster(long clusterId) {
		return ospClusterPersistence.create(clusterId);
	}

	/**
	 * Deletes the osp cluster with the primary key from the database. Also notifies the appropriate model listeners.
	 *
	 * @param clusterId the primary key of the osp cluster
	 * @return the osp cluster that was removed
	 * @throws PortalException if a osp cluster with the primary key could not be found
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public OSPCluster deleteOSPCluster(long clusterId) throws PortalException {
		return ospClusterPersistence.remove(clusterId);
	}

	/**
	 * Deletes the osp cluster from the database. Also notifies the appropriate model listeners.
	 *
	 * @param ospCluster the osp cluster
	 * @return the osp cluster that was removed
	 */
	@Indexable(type = IndexableType.DELETE)
	@Override
	public OSPCluster deleteOSPCluster(OSPCluster ospCluster) {
		return ospClusterPersistence.remove(ospCluster);
	}

	@Override
	public DynamicQuery dynamicQuery() {
		Class<?> clazz = getClass();

		return DynamicQueryFactoryUtil.forClass(
			OSPCluster.class, clazz.getClassLoader());
	}

	/**
	 * Performs a dynamic query on the database and returns the matching rows.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(DynamicQuery dynamicQuery) {
		return ospClusterPersistence.findWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Performs a dynamic query on the database and returns a range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.osp.icebreaker.model.impl.OSPClusterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @return the range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end) {

		return ospClusterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end);
	}

	/**
	 * Performs a dynamic query on the database and returns an ordered range of the matching rows.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.osp.icebreaker.model.impl.OSPClusterModelImpl</code>.
	 * </p>
	 *
	 * @param dynamicQuery the dynamic query
	 * @param start the lower bound of the range of model instances
	 * @param end the upper bound of the range of model instances (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the ordered range of matching rows
	 */
	@Override
	public <T> List<T> dynamicQuery(
		DynamicQuery dynamicQuery, int start, int end,
		OrderByComparator<T> orderByComparator) {

		return ospClusterPersistence.findWithDynamicQuery(
			dynamicQuery, start, end, orderByComparator);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(DynamicQuery dynamicQuery) {
		return ospClusterPersistence.countWithDynamicQuery(dynamicQuery);
	}

	/**
	 * Returns the number of rows matching the dynamic query.
	 *
	 * @param dynamicQuery the dynamic query
	 * @param projection the projection to apply to the query
	 * @return the number of rows matching the dynamic query
	 */
	@Override
	public long dynamicQueryCount(
		DynamicQuery dynamicQuery, Projection projection) {

		return ospClusterPersistence.countWithDynamicQuery(
			dynamicQuery, projection);
	}

	@Override
	public OSPCluster fetchOSPCluster(long clusterId) {
		return ospClusterPersistence.fetchByPrimaryKey(clusterId);
	}

	/**
	 * Returns the osp cluster matching the UUID and group.
	 *
	 * @param uuid the osp cluster's UUID
	 * @param groupId the primary key of the group
	 * @return the matching osp cluster, or <code>null</code> if a matching osp cluster could not be found
	 */
	@Override
	public OSPCluster fetchOSPClusterByUuidAndGroupId(
		String uuid, long groupId) {

		return ospClusterPersistence.fetchByUUID_G(uuid, groupId);
	}

	/**
	 * Returns the osp cluster with the primary key.
	 *
	 * @param clusterId the primary key of the osp cluster
	 * @return the osp cluster
	 * @throws PortalException if a osp cluster with the primary key could not be found
	 */
	@Override
	public OSPCluster getOSPCluster(long clusterId) throws PortalException {
		return ospClusterPersistence.findByPrimaryKey(clusterId);
	}

	@Override
	public ActionableDynamicQuery getActionableDynamicQuery() {
		ActionableDynamicQuery actionableDynamicQuery =
			new DefaultActionableDynamicQuery();

		actionableDynamicQuery.setBaseLocalService(ospClusterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(OSPCluster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("clusterId");

		return actionableDynamicQuery;
	}

	@Override
	public IndexableActionableDynamicQuery
		getIndexableActionableDynamicQuery() {

		IndexableActionableDynamicQuery indexableActionableDynamicQuery =
			new IndexableActionableDynamicQuery();

		indexableActionableDynamicQuery.setBaseLocalService(
			ospClusterLocalService);
		indexableActionableDynamicQuery.setClassLoader(getClassLoader());
		indexableActionableDynamicQuery.setModelClass(OSPCluster.class);

		indexableActionableDynamicQuery.setPrimaryKeyPropertyName("clusterId");

		return indexableActionableDynamicQuery;
	}

	protected void initActionableDynamicQuery(
		ActionableDynamicQuery actionableDynamicQuery) {

		actionableDynamicQuery.setBaseLocalService(ospClusterLocalService);
		actionableDynamicQuery.setClassLoader(getClassLoader());
		actionableDynamicQuery.setModelClass(OSPCluster.class);

		actionableDynamicQuery.setPrimaryKeyPropertyName("clusterId");
	}

	@Override
	public ExportActionableDynamicQuery getExportActionableDynamicQuery(
		final PortletDataContext portletDataContext) {

		final ExportActionableDynamicQuery exportActionableDynamicQuery =
			new ExportActionableDynamicQuery() {

				@Override
				public long performCount() throws PortalException {
					ManifestSummary manifestSummary =
						portletDataContext.getManifestSummary();

					StagedModelType stagedModelType = getStagedModelType();

					long modelAdditionCount = super.performCount();

					manifestSummary.addModelAdditionCount(
						stagedModelType, modelAdditionCount);

					long modelDeletionCount =
						ExportImportHelperUtil.getModelDeletionCount(
							portletDataContext, stagedModelType);

					manifestSummary.addModelDeletionCount(
						stagedModelType, modelDeletionCount);

					return modelAdditionCount;
				}

			};

		initActionableDynamicQuery(exportActionableDynamicQuery);

		exportActionableDynamicQuery.setAddCriteriaMethod(
			new ActionableDynamicQuery.AddCriteriaMethod() {

				@Override
				public void addCriteria(DynamicQuery dynamicQuery) {
					portletDataContext.addDateRangeCriteria(
						dynamicQuery, "modifiedDate");
				}

			});

		exportActionableDynamicQuery.setCompanyId(
			portletDataContext.getCompanyId());

		exportActionableDynamicQuery.setPerformActionMethod(
			new ActionableDynamicQuery.PerformActionMethod<OSPCluster>() {

				@Override
				public void performAction(OSPCluster ospCluster)
					throws PortalException {

					StagedModelDataHandlerUtil.exportStagedModel(
						portletDataContext, ospCluster);
				}

			});
		exportActionableDynamicQuery.setStagedModelType(
			new StagedModelType(
				PortalUtil.getClassNameId(OSPCluster.class.getName())));

		return exportActionableDynamicQuery;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel deletePersistedModel(PersistedModel persistedModel)
		throws PortalException {

		return ospClusterLocalService.deleteOSPCluster(
			(OSPCluster)persistedModel);
	}

	public BasePersistence<OSPCluster> getBasePersistence() {
		return ospClusterPersistence;
	}

	/**
	 * @throws PortalException
	 */
	@Override
	public PersistedModel getPersistedModel(Serializable primaryKeyObj)
		throws PortalException {

		return ospClusterPersistence.findByPrimaryKey(primaryKeyObj);
	}

	/**
	 * Returns all the osp clusters matching the UUID and company.
	 *
	 * @param uuid the UUID of the osp clusters
	 * @param companyId the primary key of the company
	 * @return the matching osp clusters, or an empty list if no matches were found
	 */
	@Override
	public List<OSPCluster> getOSPClustersByUuidAndCompanyId(
		String uuid, long companyId) {

		return ospClusterPersistence.findByUuid_C(uuid, companyId);
	}

	/**
	 * Returns a range of osp clusters matching the UUID and company.
	 *
	 * @param uuid the UUID of the osp clusters
	 * @param companyId the primary key of the company
	 * @param start the lower bound of the range of osp clusters
	 * @param end the upper bound of the range of osp clusters (not inclusive)
	 * @param orderByComparator the comparator to order the results by (optionally <code>null</code>)
	 * @return the range of matching osp clusters, or an empty list if no matches were found
	 */
	@Override
	public List<OSPCluster> getOSPClustersByUuidAndCompanyId(
		String uuid, long companyId, int start, int end,
		OrderByComparator<OSPCluster> orderByComparator) {

		return ospClusterPersistence.findByUuid_C(
			uuid, companyId, start, end, orderByComparator);
	}

	/**
	 * Returns the osp cluster matching the UUID and group.
	 *
	 * @param uuid the osp cluster's UUID
	 * @param groupId the primary key of the group
	 * @return the matching osp cluster
	 * @throws PortalException if a matching osp cluster could not be found
	 */
	@Override
	public OSPCluster getOSPClusterByUuidAndGroupId(String uuid, long groupId)
		throws PortalException {

		return ospClusterPersistence.findByUUID_G(uuid, groupId);
	}

	/**
	 * Returns a range of all the osp clusters.
	 *
	 * <p>
	 * Useful when paginating results. Returns a maximum of <code>end - start</code> instances. <code>start</code> and <code>end</code> are not primary keys, they are indexes in the result set. Thus, <code>0</code> refers to the first result in the set. Setting both <code>start</code> and <code>end</code> to <code>com.liferay.portal.kernel.dao.orm.QueryUtil#ALL_POS</code> will return the full result set. If <code>orderByComparator</code> is specified, then the query will include the given ORDER BY logic. If <code>orderByComparator</code> is absent, then the query will include the default ORDER BY logic from <code>com.osp.icebreaker.model.impl.OSPClusterModelImpl</code>.
	 * </p>
	 *
	 * @param start the lower bound of the range of osp clusters
	 * @param end the upper bound of the range of osp clusters (not inclusive)
	 * @return the range of osp clusters
	 */
	@Override
	public List<OSPCluster> getOSPClusters(int start, int end) {
		return ospClusterPersistence.findAll(start, end);
	}

	/**
	 * Returns the number of osp clusters.
	 *
	 * @return the number of osp clusters
	 */
	@Override
	public int getOSPClustersCount() {
		return ospClusterPersistence.countAll();
	}

	/**
	 * Updates the osp cluster in the database or adds it if it does not yet exist. Also notifies the appropriate model listeners.
	 *
	 * @param ospCluster the osp cluster
	 * @return the osp cluster that was updated
	 */
	@Indexable(type = IndexableType.REINDEX)
	@Override
	public OSPCluster updateOSPCluster(OSPCluster ospCluster) {
		return ospClusterPersistence.update(ospCluster);
	}

	@Override
	public Class<?>[] getAopInterfaces() {
		return new Class<?>[] {
			OSPClusterLocalService.class, IdentifiableOSGiService.class,
			PersistedModelLocalService.class
		};
	}

	@Override
	public void setAopProxy(Object aopProxy) {
		ospClusterLocalService = (OSPClusterLocalService)aopProxy;
	}

	/**
	 * Returns the OSGi service identifier.
	 *
	 * @return the OSGi service identifier
	 */
	@Override
	public String getOSGiServiceIdentifier() {
		return OSPClusterLocalService.class.getName();
	}

	protected Class<?> getModelClass() {
		return OSPCluster.class;
	}

	protected String getModelClassName() {
		return OSPCluster.class.getName();
	}

	/**
	 * Performs a SQL query.
	 *
	 * @param sql the sql query
	 */
	protected void runSQL(String sql) {
		try {
			DataSource dataSource = ospClusterPersistence.getDataSource();

			DB db = DBManagerUtil.getDB();

			sql = db.buildSQL(sql);
			sql = PortalUtil.transformSQL(sql);

			SqlUpdate sqlUpdate = SqlUpdateFactoryUtil.getSqlUpdate(
				dataSource, sql);

			sqlUpdate.update();
		}
		catch (Exception exception) {
			throw new SystemException(exception);
		}
	}

	@Reference
	protected IcebreakerEntryPersistence icebreakerEntryPersistence;

	@Reference
	protected JobPersistence jobPersistence;

	@Reference
	protected JobDataPersistence jobDataPersistence;

	protected OSPClusterLocalService ospClusterLocalService;

	@Reference
	protected OSPClusterPersistence ospClusterPersistence;

	@Reference
	protected com.liferay.counter.kernel.service.CounterLocalService
		counterLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ClassNameLocalService
		classNameLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.ResourceLocalService
		resourceLocalService;

	@Reference
	protected com.liferay.portal.kernel.service.UserLocalService
		userLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetEntryLocalService
		assetEntryLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetLinkLocalService
		assetLinkLocalService;

	@Reference
	protected com.liferay.asset.kernel.service.AssetTagLocalService
		assetTagLocalService;

}