create table ICEBREAKER_IcebreakerEntry (
	uuid_ VARCHAR(75) null,
	icebreakerEntryId LONG not null primary key,
	groupId LONG,
	companyId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	name VARCHAR(75) null,
	type_ VARCHAR(75) null,
	ibIp VARCHAR(75) null,
	ibPort VARCHAR(75) null,
	ibUserId VARCHAR(75) null,
	ibUserPassword VARCHAR(75) null,
	description STRING null
);

create table ICEBREAKER_Job (
	uuid_ VARCHAR(75) null,
	jobId LONG not null primary key,
	jobName VARCHAR(75) null,
	companyId LONG,
	groupId LONG,
	userId LONG,
	clusterId LONG,
	status INTEGER,
	submitId VARCHAR(75) null,
	solverExe VARCHAR(75) null,
	workingDir VARCHAR(75) null,
	runType VARCHAR(75) null,
	logFileName VARCHAR(75) null,
	title VARCHAR(75) null,
	queueName VARCHAR(75) null,
	command VARCHAR(75) null,
	referenceFiles VARCHAR(75) null,
	environmentVars VARCHAR(75) null,
	nodes INTEGER,
	processorsPerNode INTEGER,
	wallTime VARCHAR(75) null,
	eligibleTime VARCHAR(75) null,
	afterAny VARCHAR(75) null,
	afterOk VARCHAR(75) null,
	submitArgs VARCHAR(75) null,
	jobStatus INTEGER,
	reserveResults BOOLEAN,
	createDate DATE null,
	modifiedDate DATE null,
	queuedDate DATE null,
	startDate DATE null,
	completeDate DATE null,
	usedMemory VARCHAR(75) null,
	usedCpuTime VARCHAR(75) null,
	usedWalltime VARCHAR(75) null
);

create table ICEBREAKER_JobData (
	jobId LONG not null primary key,
	inputData VARCHAR(75) null
);

create table ICEBREAKER_OSPCluster (
	uuid_ VARCHAR(75) null,
	clusterId LONG not null primary key,
	companyId LONG,
	groupId LONG,
	userId LONG,
	userName VARCHAR(75) null,
	createDate DATE null,
	modifiedDate DATE null,
	status INTEGER,
	clusterName VARCHAR(75) null,
	osFamily VARCHAR(75) null,
	osName VARCHAR(75) null,
	osVersion VARCHAR(75) null,
	appRootDir VARCHAR(75) null,
	description STRING null,
	serverIp VARCHAR(75) null,
	sshPort VARCHAR(75) null,
	identificationCommand VARCHAR(75) null,
	accessMethod VARCHAR(75) null,
	authorizedId VARCHAR(75) null,
	authorizedPassword VARCHAR(75) null,
	schedulerName VARCHAR(75) null,
	schedulerVersion VARCHAR(75) null,
	schedulerClass VARCHAR(75) null,
	schedulerStatus INTEGER,
	securityLevel VARCHAR(75) null
);