/**
 * Copyright (c) 2000-present Liferay, Inc. All rights reserved.
 *
 * This library is free software; you can redistribute it and/or modify it under
 * the terms of the GNU Lesser General Public License as published by the Free
 * Software Foundation; either version 2.1 of the License, or (at your option)
 * any later version.
 *
 * This library is distributed in the hope that it will be useful, but WITHOUT
 * ANY WARRANTY; without even the implied warranty of MERCHANTABILITY or FITNESS
 * FOR A PARTICULAR PURPOSE. See the GNU Lesser General Public License for more
 * details.
 */

package com.osp.icebreaker.model.impl;

import com.liferay.expando.kernel.model.ExpandoBridge;
import com.liferay.expando.kernel.util.ExpandoBridgeFactoryUtil;
import com.liferay.exportimport.kernel.lar.StagedModelType;
import com.liferay.petra.string.StringBundler;
import com.liferay.portal.kernel.bean.AutoEscapeBeanHandler;
import com.liferay.portal.kernel.exception.PortalException;
import com.liferay.portal.kernel.json.JSON;
import com.liferay.portal.kernel.model.CacheModel;
import com.liferay.portal.kernel.model.ModelWrapper;
import com.liferay.portal.kernel.model.User;
import com.liferay.portal.kernel.model.impl.BaseModelImpl;
import com.liferay.portal.kernel.service.ServiceContext;
import com.liferay.portal.kernel.service.UserLocalServiceUtil;
import com.liferay.portal.kernel.util.DateUtil;
import com.liferay.portal.kernel.util.GetterUtil;
import com.liferay.portal.kernel.util.PortalUtil;
import com.liferay.portal.kernel.util.ProxyUtil;

import com.osp.icebreaker.model.Job;
import com.osp.icebreaker.model.JobModel;
import com.osp.icebreaker.model.JobSoap;

import java.io.Serializable;

import java.lang.reflect.Constructor;
import java.lang.reflect.InvocationHandler;

import java.sql.Types;

import java.util.ArrayList;
import java.util.Collections;
import java.util.Date;
import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.List;
import java.util.Map;
import java.util.function.BiConsumer;
import java.util.function.Function;

/**
 * The base model implementation for the Job service. Represents a row in the &quot;ICEBREAKER_Job&quot; database table, with each column mapped to a property of this class.
 *
 * <p>
 * This implementation and its corresponding interface <code>JobModel</code> exist only as a container for the default property accessors generated by ServiceBuilder. Helper methods and all application logic should be put in {@link JobImpl}.
 * </p>
 *
 * @author Jerry H. Seo
 * @see JobImpl
 * @generated
 */
@JSON(strict = true)
public class JobModelImpl extends BaseModelImpl<Job> implements JobModel {

	/*
	 * NOTE FOR DEVELOPERS:
	 *
	 * Never modify or reference this class directly. All methods that expect a job model instance should use the <code>Job</code> interface instead.
	 */
	public static final String TABLE_NAME = "ICEBREAKER_Job";

	public static final Object[][] TABLE_COLUMNS = {
		{"uuid_", Types.VARCHAR}, {"jobId", Types.BIGINT},
		{"jobName", Types.VARCHAR}, {"companyId", Types.BIGINT},
		{"groupId", Types.BIGINT}, {"userId", Types.BIGINT},
		{"clusterId", Types.BIGINT}, {"status", Types.INTEGER},
		{"submitId", Types.VARCHAR}, {"solverExe", Types.VARCHAR},
		{"workingDir", Types.VARCHAR}, {"runType", Types.VARCHAR},
		{"logFileName", Types.VARCHAR}, {"title", Types.VARCHAR},
		{"queueName", Types.VARCHAR}, {"command", Types.VARCHAR},
		{"referenceFiles", Types.VARCHAR}, {"environmentVars", Types.VARCHAR},
		{"nodes", Types.INTEGER}, {"processorsPerNode", Types.INTEGER},
		{"wallTime", Types.VARCHAR}, {"eligibleTime", Types.VARCHAR},
		{"afterAny", Types.VARCHAR}, {"afterOk", Types.VARCHAR},
		{"submitArgs", Types.VARCHAR}, {"jobStatus", Types.INTEGER},
		{"reserveResults", Types.BOOLEAN}, {"createDate", Types.TIMESTAMP},
		{"modifiedDate", Types.TIMESTAMP}, {"queuedDate", Types.TIMESTAMP},
		{"startDate", Types.TIMESTAMP}, {"completeDate", Types.TIMESTAMP},
		{"usedMemory", Types.VARCHAR}, {"usedCpuTime", Types.VARCHAR},
		{"usedWalltime", Types.VARCHAR}
	};

	public static final Map<String, Integer> TABLE_COLUMNS_MAP =
		new HashMap<String, Integer>();

	static {
		TABLE_COLUMNS_MAP.put("uuid_", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("jobName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("companyId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("groupId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("userId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("clusterId", Types.BIGINT);
		TABLE_COLUMNS_MAP.put("status", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("submitId", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("solverExe", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("workingDir", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("runType", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("logFileName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("title", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("queueName", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("command", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("referenceFiles", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("environmentVars", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("nodes", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("processorsPerNode", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("wallTime", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("eligibleTime", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("afterAny", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("afterOk", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("submitArgs", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("jobStatus", Types.INTEGER);
		TABLE_COLUMNS_MAP.put("reserveResults", Types.BOOLEAN);
		TABLE_COLUMNS_MAP.put("createDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("modifiedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("queuedDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("startDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("completeDate", Types.TIMESTAMP);
		TABLE_COLUMNS_MAP.put("usedMemory", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("usedCpuTime", Types.VARCHAR);
		TABLE_COLUMNS_MAP.put("usedWalltime", Types.VARCHAR);
	}

	public static final String TABLE_SQL_CREATE =
		"create table ICEBREAKER_Job (uuid_ VARCHAR(75) null,jobId LONG not null primary key,jobName VARCHAR(75) null,companyId LONG,groupId LONG,userId LONG,clusterId LONG,status INTEGER,submitId VARCHAR(75) null,solverExe VARCHAR(75) null,workingDir VARCHAR(75) null,runType VARCHAR(75) null,logFileName VARCHAR(75) null,title VARCHAR(75) null,queueName VARCHAR(75) null,command VARCHAR(75) null,referenceFiles VARCHAR(75) null,environmentVars VARCHAR(75) null,nodes INTEGER,processorsPerNode INTEGER,wallTime VARCHAR(75) null,eligibleTime VARCHAR(75) null,afterAny VARCHAR(75) null,afterOk VARCHAR(75) null,submitArgs VARCHAR(75) null,jobStatus INTEGER,reserveResults BOOLEAN,createDate DATE null,modifiedDate DATE null,queuedDate DATE null,startDate DATE null,completeDate DATE null,usedMemory VARCHAR(75) null,usedCpuTime VARCHAR(75) null,usedWalltime VARCHAR(75) null)";

	public static final String TABLE_SQL_DROP = "drop table ICEBREAKER_Job";

	public static final String ORDER_BY_JPQL = " ORDER BY job.createDate DESC";

	public static final String ORDER_BY_SQL =
		" ORDER BY ICEBREAKER_Job.createDate DESC";

	public static final String DATA_SOURCE = "liferayDataSource";

	public static final String SESSION_FACTORY = "liferaySessionFactory";

	public static final String TX_MANAGER = "liferayTransactionManager";

	public static final long CLUSTERID_COLUMN_BITMASK = 1L;

	public static final long COMPANYID_COLUMN_BITMASK = 2L;

	public static final long GROUPID_COLUMN_BITMASK = 4L;

	public static final long JOBSTATUS_COLUMN_BITMASK = 8L;

	public static final long QUEUENAME_COLUMN_BITMASK = 16L;

	public static final long RUNTYPE_COLUMN_BITMASK = 32L;

	public static final long STATUS_COLUMN_BITMASK = 64L;

	public static final long TITLE_COLUMN_BITMASK = 128L;

	public static final long USERID_COLUMN_BITMASK = 256L;

	public static final long UUID_COLUMN_BITMASK = 512L;

	public static final long CREATEDATE_COLUMN_BITMASK = 1024L;

	public static void setEntityCacheEnabled(boolean entityCacheEnabled) {
		_entityCacheEnabled = entityCacheEnabled;
	}

	public static void setFinderCacheEnabled(boolean finderCacheEnabled) {
		_finderCacheEnabled = finderCacheEnabled;
	}

	/**
	 * Converts the soap model instance into a normal model instance.
	 *
	 * @param soapModel the soap model instance to convert
	 * @return the normal model instance
	 */
	public static Job toModel(JobSoap soapModel) {
		if (soapModel == null) {
			return null;
		}

		Job model = new JobImpl();

		model.setUuid(soapModel.getUuid());
		model.setJobId(soapModel.getJobId());
		model.setJobName(soapModel.getJobName());
		model.setCompanyId(soapModel.getCompanyId());
		model.setGroupId(soapModel.getGroupId());
		model.setUserId(soapModel.getUserId());
		model.setClusterId(soapModel.getClusterId());
		model.setStatus(soapModel.getStatus());
		model.setSubmitId(soapModel.getSubmitId());
		model.setSolverExe(soapModel.getSolverExe());
		model.setWorkingDir(soapModel.getWorkingDir());
		model.setRunType(soapModel.getRunType());
		model.setLogFileName(soapModel.getLogFileName());
		model.setTitle(soapModel.getTitle());
		model.setQueueName(soapModel.getQueueName());
		model.setCommand(soapModel.getCommand());
		model.setReferenceFiles(soapModel.getReferenceFiles());
		model.setEnvironmentVars(soapModel.getEnvironmentVars());
		model.setNodes(soapModel.getNodes());
		model.setProcessorsPerNode(soapModel.getProcessorsPerNode());
		model.setWallTime(soapModel.getWallTime());
		model.setEligibleTime(soapModel.getEligibleTime());
		model.setAfterAny(soapModel.getAfterAny());
		model.setAfterOk(soapModel.getAfterOk());
		model.setSubmitArgs(soapModel.getSubmitArgs());
		model.setJobStatus(soapModel.getJobStatus());
		model.setReserveResults(soapModel.isReserveResults());
		model.setCreateDate(soapModel.getCreateDate());
		model.setModifiedDate(soapModel.getModifiedDate());
		model.setQueuedDate(soapModel.getQueuedDate());
		model.setStartDate(soapModel.getStartDate());
		model.setCompleteDate(soapModel.getCompleteDate());
		model.setUsedMemory(soapModel.getUsedMemory());
		model.setUsedCpuTime(soapModel.getUsedCpuTime());
		model.setUsedWalltime(soapModel.getUsedWalltime());

		return model;
	}

	/**
	 * Converts the soap model instances into normal model instances.
	 *
	 * @param soapModels the soap model instances to convert
	 * @return the normal model instances
	 */
	public static List<Job> toModels(JobSoap[] soapModels) {
		if (soapModels == null) {
			return null;
		}

		List<Job> models = new ArrayList<Job>(soapModels.length);

		for (JobSoap soapModel : soapModels) {
			models.add(toModel(soapModel));
		}

		return models;
	}

	public JobModelImpl() {
	}

	@Override
	public long getPrimaryKey() {
		return _jobId;
	}

	@Override
	public void setPrimaryKey(long primaryKey) {
		setJobId(primaryKey);
	}

	@Override
	public Serializable getPrimaryKeyObj() {
		return _jobId;
	}

	@Override
	public void setPrimaryKeyObj(Serializable primaryKeyObj) {
		setPrimaryKey(((Long)primaryKeyObj).longValue());
	}

	@Override
	public Class<?> getModelClass() {
		return Job.class;
	}

	@Override
	public String getModelClassName() {
		return Job.class.getName();
	}

	@Override
	public Map<String, Object> getModelAttributes() {
		Map<String, Object> attributes = new HashMap<String, Object>();

		Map<String, Function<Job, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		for (Map.Entry<String, Function<Job, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Job, Object> attributeGetterFunction = entry.getValue();

			attributes.put(
				attributeName, attributeGetterFunction.apply((Job)this));
		}

		attributes.put("entityCacheEnabled", isEntityCacheEnabled());
		attributes.put("finderCacheEnabled", isFinderCacheEnabled());

		return attributes;
	}

	@Override
	public void setModelAttributes(Map<String, Object> attributes) {
		Map<String, BiConsumer<Job, Object>> attributeSetterBiConsumers =
			getAttributeSetterBiConsumers();

		for (Map.Entry<String, Object> entry : attributes.entrySet()) {
			String attributeName = entry.getKey();

			BiConsumer<Job, Object> attributeSetterBiConsumer =
				attributeSetterBiConsumers.get(attributeName);

			if (attributeSetterBiConsumer != null) {
				attributeSetterBiConsumer.accept((Job)this, entry.getValue());
			}
		}
	}

	public Map<String, Function<Job, Object>> getAttributeGetterFunctions() {
		return _attributeGetterFunctions;
	}

	public Map<String, BiConsumer<Job, Object>>
		getAttributeSetterBiConsumers() {

		return _attributeSetterBiConsumers;
	}

	private static Function<InvocationHandler, Job>
		_getProxyProviderFunction() {

		Class<?> proxyClass = ProxyUtil.getProxyClass(
			Job.class.getClassLoader(), Job.class, ModelWrapper.class);

		try {
			Constructor<Job> constructor =
				(Constructor<Job>)proxyClass.getConstructor(
					InvocationHandler.class);

			return invocationHandler -> {
				try {
					return constructor.newInstance(invocationHandler);
				}
				catch (ReflectiveOperationException
							reflectiveOperationException) {

					throw new InternalError(reflectiveOperationException);
				}
			};
		}
		catch (NoSuchMethodException noSuchMethodException) {
			throw new InternalError(noSuchMethodException);
		}
	}

	private static final Map<String, Function<Job, Object>>
		_attributeGetterFunctions;
	private static final Map<String, BiConsumer<Job, Object>>
		_attributeSetterBiConsumers;

	static {
		Map<String, Function<Job, Object>> attributeGetterFunctions =
			new LinkedHashMap<String, Function<Job, Object>>();
		Map<String, BiConsumer<Job, ?>> attributeSetterBiConsumers =
			new LinkedHashMap<String, BiConsumer<Job, ?>>();

		attributeGetterFunctions.put("uuid", Job::getUuid);
		attributeSetterBiConsumers.put(
			"uuid", (BiConsumer<Job, String>)Job::setUuid);
		attributeGetterFunctions.put("jobId", Job::getJobId);
		attributeSetterBiConsumers.put(
			"jobId", (BiConsumer<Job, Long>)Job::setJobId);
		attributeGetterFunctions.put("jobName", Job::getJobName);
		attributeSetterBiConsumers.put(
			"jobName", (BiConsumer<Job, String>)Job::setJobName);
		attributeGetterFunctions.put("companyId", Job::getCompanyId);
		attributeSetterBiConsumers.put(
			"companyId", (BiConsumer<Job, Long>)Job::setCompanyId);
		attributeGetterFunctions.put("groupId", Job::getGroupId);
		attributeSetterBiConsumers.put(
			"groupId", (BiConsumer<Job, Long>)Job::setGroupId);
		attributeGetterFunctions.put("userId", Job::getUserId);
		attributeSetterBiConsumers.put(
			"userId", (BiConsumer<Job, Long>)Job::setUserId);
		attributeGetterFunctions.put("clusterId", Job::getClusterId);
		attributeSetterBiConsumers.put(
			"clusterId", (BiConsumer<Job, Long>)Job::setClusterId);
		attributeGetterFunctions.put("status", Job::getStatus);
		attributeSetterBiConsumers.put(
			"status", (BiConsumer<Job, Integer>)Job::setStatus);
		attributeGetterFunctions.put("submitId", Job::getSubmitId);
		attributeSetterBiConsumers.put(
			"submitId", (BiConsumer<Job, String>)Job::setSubmitId);
		attributeGetterFunctions.put("solverExe", Job::getSolverExe);
		attributeSetterBiConsumers.put(
			"solverExe", (BiConsumer<Job, String>)Job::setSolverExe);
		attributeGetterFunctions.put("workingDir", Job::getWorkingDir);
		attributeSetterBiConsumers.put(
			"workingDir", (BiConsumer<Job, String>)Job::setWorkingDir);
		attributeGetterFunctions.put("runType", Job::getRunType);
		attributeSetterBiConsumers.put(
			"runType", (BiConsumer<Job, String>)Job::setRunType);
		attributeGetterFunctions.put("logFileName", Job::getLogFileName);
		attributeSetterBiConsumers.put(
			"logFileName", (BiConsumer<Job, String>)Job::setLogFileName);
		attributeGetterFunctions.put("title", Job::getTitle);
		attributeSetterBiConsumers.put(
			"title", (BiConsumer<Job, String>)Job::setTitle);
		attributeGetterFunctions.put("queueName", Job::getQueueName);
		attributeSetterBiConsumers.put(
			"queueName", (BiConsumer<Job, String>)Job::setQueueName);
		attributeGetterFunctions.put("command", Job::getCommand);
		attributeSetterBiConsumers.put(
			"command", (BiConsumer<Job, String>)Job::setCommand);
		attributeGetterFunctions.put("referenceFiles", Job::getReferenceFiles);
		attributeSetterBiConsumers.put(
			"referenceFiles", (BiConsumer<Job, String>)Job::setReferenceFiles);
		attributeGetterFunctions.put(
			"environmentVars", Job::getEnvironmentVars);
		attributeSetterBiConsumers.put(
			"environmentVars",
			(BiConsumer<Job, String>)Job::setEnvironmentVars);
		attributeGetterFunctions.put("nodes", Job::getNodes);
		attributeSetterBiConsumers.put(
			"nodes", (BiConsumer<Job, Integer>)Job::setNodes);
		attributeGetterFunctions.put(
			"processorsPerNode", Job::getProcessorsPerNode);
		attributeSetterBiConsumers.put(
			"processorsPerNode",
			(BiConsumer<Job, Integer>)Job::setProcessorsPerNode);
		attributeGetterFunctions.put("wallTime", Job::getWallTime);
		attributeSetterBiConsumers.put(
			"wallTime", (BiConsumer<Job, String>)Job::setWallTime);
		attributeGetterFunctions.put("eligibleTime", Job::getEligibleTime);
		attributeSetterBiConsumers.put(
			"eligibleTime", (BiConsumer<Job, String>)Job::setEligibleTime);
		attributeGetterFunctions.put("afterAny", Job::getAfterAny);
		attributeSetterBiConsumers.put(
			"afterAny", (BiConsumer<Job, String>)Job::setAfterAny);
		attributeGetterFunctions.put("afterOk", Job::getAfterOk);
		attributeSetterBiConsumers.put(
			"afterOk", (BiConsumer<Job, String>)Job::setAfterOk);
		attributeGetterFunctions.put("submitArgs", Job::getSubmitArgs);
		attributeSetterBiConsumers.put(
			"submitArgs", (BiConsumer<Job, String>)Job::setSubmitArgs);
		attributeGetterFunctions.put("jobStatus", Job::getJobStatus);
		attributeSetterBiConsumers.put(
			"jobStatus", (BiConsumer<Job, Integer>)Job::setJobStatus);
		attributeGetterFunctions.put("reserveResults", Job::getReserveResults);
		attributeSetterBiConsumers.put(
			"reserveResults", (BiConsumer<Job, Boolean>)Job::setReserveResults);
		attributeGetterFunctions.put("createDate", Job::getCreateDate);
		attributeSetterBiConsumers.put(
			"createDate", (BiConsumer<Job, Date>)Job::setCreateDate);
		attributeGetterFunctions.put("modifiedDate", Job::getModifiedDate);
		attributeSetterBiConsumers.put(
			"modifiedDate", (BiConsumer<Job, Date>)Job::setModifiedDate);
		attributeGetterFunctions.put("queuedDate", Job::getQueuedDate);
		attributeSetterBiConsumers.put(
			"queuedDate", (BiConsumer<Job, Date>)Job::setQueuedDate);
		attributeGetterFunctions.put("startDate", Job::getStartDate);
		attributeSetterBiConsumers.put(
			"startDate", (BiConsumer<Job, Date>)Job::setStartDate);
		attributeGetterFunctions.put("completeDate", Job::getCompleteDate);
		attributeSetterBiConsumers.put(
			"completeDate", (BiConsumer<Job, Date>)Job::setCompleteDate);
		attributeGetterFunctions.put("usedMemory", Job::getUsedMemory);
		attributeSetterBiConsumers.put(
			"usedMemory", (BiConsumer<Job, String>)Job::setUsedMemory);
		attributeGetterFunctions.put("usedCpuTime", Job::getUsedCpuTime);
		attributeSetterBiConsumers.put(
			"usedCpuTime", (BiConsumer<Job, String>)Job::setUsedCpuTime);
		attributeGetterFunctions.put("usedWalltime", Job::getUsedWalltime);
		attributeSetterBiConsumers.put(
			"usedWalltime", (BiConsumer<Job, String>)Job::setUsedWalltime);

		_attributeGetterFunctions = Collections.unmodifiableMap(
			attributeGetterFunctions);
		_attributeSetterBiConsumers = Collections.unmodifiableMap(
			(Map)attributeSetterBiConsumers);
	}

	@JSON
	@Override
	public String getUuid() {
		if (_uuid == null) {
			return "";
		}
		else {
			return _uuid;
		}
	}

	@Override
	public void setUuid(String uuid) {
		_columnBitmask |= UUID_COLUMN_BITMASK;

		if (_originalUuid == null) {
			_originalUuid = _uuid;
		}

		_uuid = uuid;
	}

	public String getOriginalUuid() {
		return GetterUtil.getString(_originalUuid);
	}

	@JSON
	@Override
	public long getJobId() {
		return _jobId;
	}

	@Override
	public void setJobId(long jobId) {
		_jobId = jobId;
	}

	@JSON
	@Override
	public String getJobName() {
		if (_jobName == null) {
			return "";
		}
		else {
			return _jobName;
		}
	}

	@Override
	public void setJobName(String jobName) {
		_jobName = jobName;
	}

	@JSON
	@Override
	public long getCompanyId() {
		return _companyId;
	}

	@Override
	public void setCompanyId(long companyId) {
		_columnBitmask |= COMPANYID_COLUMN_BITMASK;

		if (!_setOriginalCompanyId) {
			_setOriginalCompanyId = true;

			_originalCompanyId = _companyId;
		}

		_companyId = companyId;
	}

	public long getOriginalCompanyId() {
		return _originalCompanyId;
	}

	@JSON
	@Override
	public long getGroupId() {
		return _groupId;
	}

	@Override
	public void setGroupId(long groupId) {
		_columnBitmask |= GROUPID_COLUMN_BITMASK;

		if (!_setOriginalGroupId) {
			_setOriginalGroupId = true;

			_originalGroupId = _groupId;
		}

		_groupId = groupId;
	}

	public long getOriginalGroupId() {
		return _originalGroupId;
	}

	@JSON
	@Override
	public long getUserId() {
		return _userId;
	}

	@Override
	public void setUserId(long userId) {
		_columnBitmask |= USERID_COLUMN_BITMASK;

		if (!_setOriginalUserId) {
			_setOriginalUserId = true;

			_originalUserId = _userId;
		}

		_userId = userId;
	}

	@Override
	public String getUserUuid() {
		try {
			User user = UserLocalServiceUtil.getUserById(getUserId());

			return user.getUuid();
		}
		catch (PortalException portalException) {
			return "";
		}
	}

	@Override
	public void setUserUuid(String userUuid) {
	}

	public long getOriginalUserId() {
		return _originalUserId;
	}

	@JSON
	@Override
	public long getClusterId() {
		return _clusterId;
	}

	@Override
	public void setClusterId(long clusterId) {
		_columnBitmask |= CLUSTERID_COLUMN_BITMASK;

		if (!_setOriginalClusterId) {
			_setOriginalClusterId = true;

			_originalClusterId = _clusterId;
		}

		_clusterId = clusterId;
	}

	public long getOriginalClusterId() {
		return _originalClusterId;
	}

	@JSON
	@Override
	public int getStatus() {
		return _status;
	}

	@Override
	public void setStatus(int status) {
		_columnBitmask |= STATUS_COLUMN_BITMASK;

		if (!_setOriginalStatus) {
			_setOriginalStatus = true;

			_originalStatus = _status;
		}

		_status = status;
	}

	public int getOriginalStatus() {
		return _originalStatus;
	}

	@JSON
	@Override
	public String getSubmitId() {
		if (_submitId == null) {
			return "";
		}
		else {
			return _submitId;
		}
	}

	@Override
	public void setSubmitId(String submitId) {
		_submitId = submitId;
	}

	@JSON
	@Override
	public String getSolverExe() {
		if (_solverExe == null) {
			return "";
		}
		else {
			return _solverExe;
		}
	}

	@Override
	public void setSolverExe(String solverExe) {
		_solverExe = solverExe;
	}

	@JSON
	@Override
	public String getWorkingDir() {
		if (_workingDir == null) {
			return "";
		}
		else {
			return _workingDir;
		}
	}

	@Override
	public void setWorkingDir(String workingDir) {
		_workingDir = workingDir;
	}

	@JSON
	@Override
	public String getRunType() {
		if (_runType == null) {
			return "";
		}
		else {
			return _runType;
		}
	}

	@Override
	public void setRunType(String runType) {
		_columnBitmask |= RUNTYPE_COLUMN_BITMASK;

		if (_originalRunType == null) {
			_originalRunType = _runType;
		}

		_runType = runType;
	}

	public String getOriginalRunType() {
		return GetterUtil.getString(_originalRunType);
	}

	@JSON
	@Override
	public String getLogFileName() {
		if (_logFileName == null) {
			return "";
		}
		else {
			return _logFileName;
		}
	}

	@Override
	public void setLogFileName(String logFileName) {
		_logFileName = logFileName;
	}

	@JSON
	@Override
	public String getTitle() {
		if (_title == null) {
			return "";
		}
		else {
			return _title;
		}
	}

	@Override
	public void setTitle(String title) {
		_columnBitmask |= TITLE_COLUMN_BITMASK;

		if (_originalTitle == null) {
			_originalTitle = _title;
		}

		_title = title;
	}

	public String getOriginalTitle() {
		return GetterUtil.getString(_originalTitle);
	}

	@JSON
	@Override
	public String getQueueName() {
		if (_queueName == null) {
			return "";
		}
		else {
			return _queueName;
		}
	}

	@Override
	public void setQueueName(String queueName) {
		_columnBitmask |= QUEUENAME_COLUMN_BITMASK;

		if (_originalQueueName == null) {
			_originalQueueName = _queueName;
		}

		_queueName = queueName;
	}

	public String getOriginalQueueName() {
		return GetterUtil.getString(_originalQueueName);
	}

	@JSON
	@Override
	public String getCommand() {
		if (_command == null) {
			return "";
		}
		else {
			return _command;
		}
	}

	@Override
	public void setCommand(String command) {
		_command = command;
	}

	@JSON
	@Override
	public String getReferenceFiles() {
		if (_referenceFiles == null) {
			return "";
		}
		else {
			return _referenceFiles;
		}
	}

	@Override
	public void setReferenceFiles(String referenceFiles) {
		_referenceFiles = referenceFiles;
	}

	@JSON
	@Override
	public String getEnvironmentVars() {
		if (_environmentVars == null) {
			return "";
		}
		else {
			return _environmentVars;
		}
	}

	@Override
	public void setEnvironmentVars(String environmentVars) {
		_environmentVars = environmentVars;
	}

	@JSON
	@Override
	public int getNodes() {
		return _nodes;
	}

	@Override
	public void setNodes(int nodes) {
		_nodes = nodes;
	}

	@JSON
	@Override
	public int getProcessorsPerNode() {
		return _processorsPerNode;
	}

	@Override
	public void setProcessorsPerNode(int processorsPerNode) {
		_processorsPerNode = processorsPerNode;
	}

	@JSON
	@Override
	public String getWallTime() {
		if (_wallTime == null) {
			return "";
		}
		else {
			return _wallTime;
		}
	}

	@Override
	public void setWallTime(String wallTime) {
		_wallTime = wallTime;
	}

	@JSON
	@Override
	public String getEligibleTime() {
		if (_eligibleTime == null) {
			return "";
		}
		else {
			return _eligibleTime;
		}
	}

	@Override
	public void setEligibleTime(String eligibleTime) {
		_eligibleTime = eligibleTime;
	}

	@JSON
	@Override
	public String getAfterAny() {
		if (_afterAny == null) {
			return "";
		}
		else {
			return _afterAny;
		}
	}

	@Override
	public void setAfterAny(String afterAny) {
		_afterAny = afterAny;
	}

	@JSON
	@Override
	public String getAfterOk() {
		if (_afterOk == null) {
			return "";
		}
		else {
			return _afterOk;
		}
	}

	@Override
	public void setAfterOk(String afterOk) {
		_afterOk = afterOk;
	}

	@JSON
	@Override
	public String getSubmitArgs() {
		if (_submitArgs == null) {
			return "";
		}
		else {
			return _submitArgs;
		}
	}

	@Override
	public void setSubmitArgs(String submitArgs) {
		_submitArgs = submitArgs;
	}

	@JSON
	@Override
	public int getJobStatus() {
		return _jobStatus;
	}

	@Override
	public void setJobStatus(int jobStatus) {
		_columnBitmask |= JOBSTATUS_COLUMN_BITMASK;

		if (!_setOriginalJobStatus) {
			_setOriginalJobStatus = true;

			_originalJobStatus = _jobStatus;
		}

		_jobStatus = jobStatus;
	}

	public int getOriginalJobStatus() {
		return _originalJobStatus;
	}

	@JSON
	@Override
	public boolean getReserveResults() {
		return _reserveResults;
	}

	@JSON
	@Override
	public boolean isReserveResults() {
		return _reserveResults;
	}

	@Override
	public void setReserveResults(boolean reserveResults) {
		_reserveResults = reserveResults;
	}

	@JSON
	@Override
	public Date getCreateDate() {
		return _createDate;
	}

	@Override
	public void setCreateDate(Date createDate) {
		_columnBitmask = -1L;

		_createDate = createDate;
	}

	@JSON
	@Override
	public Date getModifiedDate() {
		return _modifiedDate;
	}

	public boolean hasSetModifiedDate() {
		return _setModifiedDate;
	}

	@Override
	public void setModifiedDate(Date modifiedDate) {
		_setModifiedDate = true;

		_modifiedDate = modifiedDate;
	}

	@JSON
	@Override
	public Date getQueuedDate() {
		return _queuedDate;
	}

	@Override
	public void setQueuedDate(Date queuedDate) {
		_queuedDate = queuedDate;
	}

	@JSON
	@Override
	public Date getStartDate() {
		return _startDate;
	}

	@Override
	public void setStartDate(Date startDate) {
		_startDate = startDate;
	}

	@JSON
	@Override
	public Date getCompleteDate() {
		return _completeDate;
	}

	@Override
	public void setCompleteDate(Date completeDate) {
		_completeDate = completeDate;
	}

	@JSON
	@Override
	public String getUsedMemory() {
		if (_usedMemory == null) {
			return "";
		}
		else {
			return _usedMemory;
		}
	}

	@Override
	public void setUsedMemory(String usedMemory) {
		_usedMemory = usedMemory;
	}

	@JSON
	@Override
	public String getUsedCpuTime() {
		if (_usedCpuTime == null) {
			return "";
		}
		else {
			return _usedCpuTime;
		}
	}

	@Override
	public void setUsedCpuTime(String usedCpuTime) {
		_usedCpuTime = usedCpuTime;
	}

	@JSON
	@Override
	public String getUsedWalltime() {
		if (_usedWalltime == null) {
			return "";
		}
		else {
			return _usedWalltime;
		}
	}

	@Override
	public void setUsedWalltime(String usedWalltime) {
		_usedWalltime = usedWalltime;
	}

	@Override
	public StagedModelType getStagedModelType() {
		return new StagedModelType(
			PortalUtil.getClassNameId(Job.class.getName()));
	}

	public long getColumnBitmask() {
		return _columnBitmask;
	}

	@Override
	public ExpandoBridge getExpandoBridge() {
		return ExpandoBridgeFactoryUtil.getExpandoBridge(
			getCompanyId(), Job.class.getName(), getPrimaryKey());
	}

	@Override
	public void setExpandoBridgeAttributes(ServiceContext serviceContext) {
		ExpandoBridge expandoBridge = getExpandoBridge();

		expandoBridge.setAttributes(serviceContext);
	}

	@Override
	public Job toEscapedModel() {
		if (_escapedModel == null) {
			Function<InvocationHandler, Job> escapedModelProxyProviderFunction =
				EscapedModelProxyProviderFunctionHolder.
					_escapedModelProxyProviderFunction;

			_escapedModel = escapedModelProxyProviderFunction.apply(
				new AutoEscapeBeanHandler(this));
		}

		return _escapedModel;
	}

	@Override
	public Object clone() {
		JobImpl jobImpl = new JobImpl();

		jobImpl.setUuid(getUuid());
		jobImpl.setJobId(getJobId());
		jobImpl.setJobName(getJobName());
		jobImpl.setCompanyId(getCompanyId());
		jobImpl.setGroupId(getGroupId());
		jobImpl.setUserId(getUserId());
		jobImpl.setClusterId(getClusterId());
		jobImpl.setStatus(getStatus());
		jobImpl.setSubmitId(getSubmitId());
		jobImpl.setSolverExe(getSolverExe());
		jobImpl.setWorkingDir(getWorkingDir());
		jobImpl.setRunType(getRunType());
		jobImpl.setLogFileName(getLogFileName());
		jobImpl.setTitle(getTitle());
		jobImpl.setQueueName(getQueueName());
		jobImpl.setCommand(getCommand());
		jobImpl.setReferenceFiles(getReferenceFiles());
		jobImpl.setEnvironmentVars(getEnvironmentVars());
		jobImpl.setNodes(getNodes());
		jobImpl.setProcessorsPerNode(getProcessorsPerNode());
		jobImpl.setWallTime(getWallTime());
		jobImpl.setEligibleTime(getEligibleTime());
		jobImpl.setAfterAny(getAfterAny());
		jobImpl.setAfterOk(getAfterOk());
		jobImpl.setSubmitArgs(getSubmitArgs());
		jobImpl.setJobStatus(getJobStatus());
		jobImpl.setReserveResults(isReserveResults());
		jobImpl.setCreateDate(getCreateDate());
		jobImpl.setModifiedDate(getModifiedDate());
		jobImpl.setQueuedDate(getQueuedDate());
		jobImpl.setStartDate(getStartDate());
		jobImpl.setCompleteDate(getCompleteDate());
		jobImpl.setUsedMemory(getUsedMemory());
		jobImpl.setUsedCpuTime(getUsedCpuTime());
		jobImpl.setUsedWalltime(getUsedWalltime());

		jobImpl.resetOriginalValues();

		return jobImpl;
	}

	@Override
	public int compareTo(Job job) {
		int value = 0;

		value = DateUtil.compareTo(getCreateDate(), job.getCreateDate());

		value = value * -1;

		if (value != 0) {
			return value;
		}

		return 0;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj) {
			return true;
		}

		if (!(obj instanceof Job)) {
			return false;
		}

		Job job = (Job)obj;

		long primaryKey = job.getPrimaryKey();

		if (getPrimaryKey() == primaryKey) {
			return true;
		}
		else {
			return false;
		}
	}

	@Override
	public int hashCode() {
		return (int)getPrimaryKey();
	}

	@Override
	public boolean isEntityCacheEnabled() {
		return _entityCacheEnabled;
	}

	@Override
	public boolean isFinderCacheEnabled() {
		return _finderCacheEnabled;
	}

	@Override
	public void resetOriginalValues() {
		JobModelImpl jobModelImpl = this;

		jobModelImpl._originalUuid = jobModelImpl._uuid;

		jobModelImpl._originalCompanyId = jobModelImpl._companyId;

		jobModelImpl._setOriginalCompanyId = false;

		jobModelImpl._originalGroupId = jobModelImpl._groupId;

		jobModelImpl._setOriginalGroupId = false;

		jobModelImpl._originalUserId = jobModelImpl._userId;

		jobModelImpl._setOriginalUserId = false;

		jobModelImpl._originalClusterId = jobModelImpl._clusterId;

		jobModelImpl._setOriginalClusterId = false;

		jobModelImpl._originalStatus = jobModelImpl._status;

		jobModelImpl._setOriginalStatus = false;

		jobModelImpl._originalRunType = jobModelImpl._runType;

		jobModelImpl._originalTitle = jobModelImpl._title;

		jobModelImpl._originalQueueName = jobModelImpl._queueName;

		jobModelImpl._originalJobStatus = jobModelImpl._jobStatus;

		jobModelImpl._setOriginalJobStatus = false;

		jobModelImpl._setModifiedDate = false;

		jobModelImpl._columnBitmask = 0;
	}

	@Override
	public CacheModel<Job> toCacheModel() {
		JobCacheModel jobCacheModel = new JobCacheModel();

		jobCacheModel.uuid = getUuid();

		String uuid = jobCacheModel.uuid;

		if ((uuid != null) && (uuid.length() == 0)) {
			jobCacheModel.uuid = null;
		}

		jobCacheModel.jobId = getJobId();

		jobCacheModel.jobName = getJobName();

		String jobName = jobCacheModel.jobName;

		if ((jobName != null) && (jobName.length() == 0)) {
			jobCacheModel.jobName = null;
		}

		jobCacheModel.companyId = getCompanyId();

		jobCacheModel.groupId = getGroupId();

		jobCacheModel.userId = getUserId();

		jobCacheModel.clusterId = getClusterId();

		jobCacheModel.status = getStatus();

		jobCacheModel.submitId = getSubmitId();

		String submitId = jobCacheModel.submitId;

		if ((submitId != null) && (submitId.length() == 0)) {
			jobCacheModel.submitId = null;
		}

		jobCacheModel.solverExe = getSolverExe();

		String solverExe = jobCacheModel.solverExe;

		if ((solverExe != null) && (solverExe.length() == 0)) {
			jobCacheModel.solverExe = null;
		}

		jobCacheModel.workingDir = getWorkingDir();

		String workingDir = jobCacheModel.workingDir;

		if ((workingDir != null) && (workingDir.length() == 0)) {
			jobCacheModel.workingDir = null;
		}

		jobCacheModel.runType = getRunType();

		String runType = jobCacheModel.runType;

		if ((runType != null) && (runType.length() == 0)) {
			jobCacheModel.runType = null;
		}

		jobCacheModel.logFileName = getLogFileName();

		String logFileName = jobCacheModel.logFileName;

		if ((logFileName != null) && (logFileName.length() == 0)) {
			jobCacheModel.logFileName = null;
		}

		jobCacheModel.title = getTitle();

		String title = jobCacheModel.title;

		if ((title != null) && (title.length() == 0)) {
			jobCacheModel.title = null;
		}

		jobCacheModel.queueName = getQueueName();

		String queueName = jobCacheModel.queueName;

		if ((queueName != null) && (queueName.length() == 0)) {
			jobCacheModel.queueName = null;
		}

		jobCacheModel.command = getCommand();

		String command = jobCacheModel.command;

		if ((command != null) && (command.length() == 0)) {
			jobCacheModel.command = null;
		}

		jobCacheModel.referenceFiles = getReferenceFiles();

		String referenceFiles = jobCacheModel.referenceFiles;

		if ((referenceFiles != null) && (referenceFiles.length() == 0)) {
			jobCacheModel.referenceFiles = null;
		}

		jobCacheModel.environmentVars = getEnvironmentVars();

		String environmentVars = jobCacheModel.environmentVars;

		if ((environmentVars != null) && (environmentVars.length() == 0)) {
			jobCacheModel.environmentVars = null;
		}

		jobCacheModel.nodes = getNodes();

		jobCacheModel.processorsPerNode = getProcessorsPerNode();

		jobCacheModel.wallTime = getWallTime();

		String wallTime = jobCacheModel.wallTime;

		if ((wallTime != null) && (wallTime.length() == 0)) {
			jobCacheModel.wallTime = null;
		}

		jobCacheModel.eligibleTime = getEligibleTime();

		String eligibleTime = jobCacheModel.eligibleTime;

		if ((eligibleTime != null) && (eligibleTime.length() == 0)) {
			jobCacheModel.eligibleTime = null;
		}

		jobCacheModel.afterAny = getAfterAny();

		String afterAny = jobCacheModel.afterAny;

		if ((afterAny != null) && (afterAny.length() == 0)) {
			jobCacheModel.afterAny = null;
		}

		jobCacheModel.afterOk = getAfterOk();

		String afterOk = jobCacheModel.afterOk;

		if ((afterOk != null) && (afterOk.length() == 0)) {
			jobCacheModel.afterOk = null;
		}

		jobCacheModel.submitArgs = getSubmitArgs();

		String submitArgs = jobCacheModel.submitArgs;

		if ((submitArgs != null) && (submitArgs.length() == 0)) {
			jobCacheModel.submitArgs = null;
		}

		jobCacheModel.jobStatus = getJobStatus();

		jobCacheModel.reserveResults = isReserveResults();

		Date createDate = getCreateDate();

		if (createDate != null) {
			jobCacheModel.createDate = createDate.getTime();
		}
		else {
			jobCacheModel.createDate = Long.MIN_VALUE;
		}

		Date modifiedDate = getModifiedDate();

		if (modifiedDate != null) {
			jobCacheModel.modifiedDate = modifiedDate.getTime();
		}
		else {
			jobCacheModel.modifiedDate = Long.MIN_VALUE;
		}

		Date queuedDate = getQueuedDate();

		if (queuedDate != null) {
			jobCacheModel.queuedDate = queuedDate.getTime();
		}
		else {
			jobCacheModel.queuedDate = Long.MIN_VALUE;
		}

		Date startDate = getStartDate();

		if (startDate != null) {
			jobCacheModel.startDate = startDate.getTime();
		}
		else {
			jobCacheModel.startDate = Long.MIN_VALUE;
		}

		Date completeDate = getCompleteDate();

		if (completeDate != null) {
			jobCacheModel.completeDate = completeDate.getTime();
		}
		else {
			jobCacheModel.completeDate = Long.MIN_VALUE;
		}

		jobCacheModel.usedMemory = getUsedMemory();

		String usedMemory = jobCacheModel.usedMemory;

		if ((usedMemory != null) && (usedMemory.length() == 0)) {
			jobCacheModel.usedMemory = null;
		}

		jobCacheModel.usedCpuTime = getUsedCpuTime();

		String usedCpuTime = jobCacheModel.usedCpuTime;

		if ((usedCpuTime != null) && (usedCpuTime.length() == 0)) {
			jobCacheModel.usedCpuTime = null;
		}

		jobCacheModel.usedWalltime = getUsedWalltime();

		String usedWalltime = jobCacheModel.usedWalltime;

		if ((usedWalltime != null) && (usedWalltime.length() == 0)) {
			jobCacheModel.usedWalltime = null;
		}

		return jobCacheModel;
	}

	@Override
	public String toString() {
		Map<String, Function<Job, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			4 * attributeGetterFunctions.size() + 2);

		sb.append("{");

		for (Map.Entry<String, Function<Job, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Job, Object> attributeGetterFunction = entry.getValue();

			sb.append(attributeName);
			sb.append("=");
			sb.append(attributeGetterFunction.apply((Job)this));
			sb.append(", ");
		}

		if (sb.index() > 1) {
			sb.setIndex(sb.index() - 1);
		}

		sb.append("}");

		return sb.toString();
	}

	@Override
	public String toXmlString() {
		Map<String, Function<Job, Object>> attributeGetterFunctions =
			getAttributeGetterFunctions();

		StringBundler sb = new StringBundler(
			5 * attributeGetterFunctions.size() + 4);

		sb.append("<model><model-name>");
		sb.append(getModelClassName());
		sb.append("</model-name>");

		for (Map.Entry<String, Function<Job, Object>> entry :
				attributeGetterFunctions.entrySet()) {

			String attributeName = entry.getKey();
			Function<Job, Object> attributeGetterFunction = entry.getValue();

			sb.append("<column><column-name>");
			sb.append(attributeName);
			sb.append("</column-name><column-value><![CDATA[");
			sb.append(attributeGetterFunction.apply((Job)this));
			sb.append("]]></column-value></column>");
		}

		sb.append("</model>");

		return sb.toString();
	}

	private static class EscapedModelProxyProviderFunctionHolder {

		private static final Function<InvocationHandler, Job>
			_escapedModelProxyProviderFunction = _getProxyProviderFunction();

	}

	private static boolean _entityCacheEnabled;
	private static boolean _finderCacheEnabled;

	private String _uuid;
	private String _originalUuid;
	private long _jobId;
	private String _jobName;
	private long _companyId;
	private long _originalCompanyId;
	private boolean _setOriginalCompanyId;
	private long _groupId;
	private long _originalGroupId;
	private boolean _setOriginalGroupId;
	private long _userId;
	private long _originalUserId;
	private boolean _setOriginalUserId;
	private long _clusterId;
	private long _originalClusterId;
	private boolean _setOriginalClusterId;
	private int _status;
	private int _originalStatus;
	private boolean _setOriginalStatus;
	private String _submitId;
	private String _solverExe;
	private String _workingDir;
	private String _runType;
	private String _originalRunType;
	private String _logFileName;
	private String _title;
	private String _originalTitle;
	private String _queueName;
	private String _originalQueueName;
	private String _command;
	private String _referenceFiles;
	private String _environmentVars;
	private int _nodes;
	private int _processorsPerNode;
	private String _wallTime;
	private String _eligibleTime;
	private String _afterAny;
	private String _afterOk;
	private String _submitArgs;
	private int _jobStatus;
	private int _originalJobStatus;
	private boolean _setOriginalJobStatus;
	private boolean _reserveResults;
	private Date _createDate;
	private Date _modifiedDate;
	private boolean _setModifiedDate;
	private Date _queuedDate;
	private Date _startDate;
	private Date _completeDate;
	private String _usedMemory;
	private String _usedCpuTime;
	private String _usedWalltime;
	private long _columnBitmask;
	private Job _escapedModel;

}